- name: Create a user prometheus
  ansible.builtin.user:
    name: prometheus
    create_home: no
    shell: /bin/false
    system: true

- name: Download prometheus
  ansible.builtin.get_url:
    url: https://github.com/prometheus/prometheus/releases/download/v2.45.0/prometheus-2.45.0.linux-amd64.tar.gz
    dest: /tmp/prometheus.tar.gz

- name: Extract prometheus tar file
  ansible.builtin.unarchive:
    src: /tmp/prometheus.tar.gz
    dest: /tmp
    remote_src: yes